name: Release Theme

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: bun merge.js

      - name: Create PR
        uses: huacnlee/zed-extension-action@v1
        with:
          extension-name: min-theme
          push-to: phibr0/extensions
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
